Update patch set 1
Patch Set 1: Verified+1 Code-Review+2

Should fix the build problem with system dump on Oracle VM:

org.eclipse.mat.SnapshotException: Agent initialization
	at org.eclipse.mat.ibmvm.acquire.IBMDumpProvider$AgentLoader.throwFailed(IBMDumpProvider.java:594)
	at org.eclipse.mat.ibmvm.acquire.IBMDumpProvider.acquireDump(IBMDumpProvider.java:808)
	at org.eclipse.mat.ibmvm.acquire.IBMDumpProvider.acquireDump(IBMDumpProvider.java:753)
	at org.eclipse.mat.tests.acquire.AcquireDumpTest.test3(AcquireDumpTest.java:127)
Caused by: org.eclipse.mat.ibmvm.acquire.IBMDumpProvider$AgentInitializationException: Agent JAR loaded but agent failed to initialize returnValue=0
	at org.eclipse.mat.ibmvm.acquire.IBMDumpProvider$VirtualMachine.loadAgent(IBMDumpProvider.java:454)
	at org.eclipse.mat.ibmvm.acquire.IBMDumpProvider$AgentLoader.run(IBMDumpProvider.java:549)

Patch-set: 1
Reviewer: Gerrit User 65230 <65230@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Verified=+1
Label: Code-Review=+2